/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: the database answers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The highest indexed block */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tip: components["schemas"]["Tip"] | null;
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest blocks, newest first */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, 1 to 100 (default 20) */
                    limit?: string;
                    /** @description The `next` value of the previous page; omit for the first page */
                    before?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            blocks: components["schemas"]["BlockSummary"][];
                            next: number | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blocks/{hashOrHeight}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A block by height or hash */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hashOrHeight: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Block"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blocks/{hash}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A block's transactions, in block order */
        get: {
            parameters: {
                query?: {
                    /** @description Page size, 1 to 100 (default 25) */
                    limit?: string;
                    /** @description The `next` value of the previous page; omit for the first page */
                    after?: string;
                };
                header?: never;
                path: {
                    hash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transactions: components["schemas"]["TransactionSummary"][];
                            next: number | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{txid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A transaction with its inputs, outputs and spends */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    txid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find a block (height or hash) or a transaction (txid) */
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResult"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemInput: {
            type: string;
            title: string;
            status: number;
            detail?: string;
        };
        BlockSummaryInput: {
            height: number;
            hash: string;
            time: number;
            txCount: number;
            size: number;
            weight: number;
            totalFeeSat: number;
        };
        BlockInput: {
            height: number;
            hash: string;
            prevHash: string | null;
            nextBlockHash: string | null;
            confirmations: number;
            merkleRoot: string;
            version: number;
            bits: string;
            nonce: number;
            difficulty: number;
            time: number;
            medianTime: number;
            size: number;
            strippedSize: number;
            weight: number;
            txCount: number;
            subsidySat: number;
            totalFeeSat: number;
            rewardSat: number;
        };
        TransactionSummaryInput: {
            txid: string;
            position: number;
            isCoinbase: boolean;
            feeSat: number | null;
            vsize: number;
            inputCount: number;
            outputCount: number;
            totalInSat: number | null;
            totalOutSat: number;
        };
        ScriptInput: {
            hex: string;
            asm: string;
        };
        TransactionInput: {
            txid: string;
            blockHash: string;
            blockHeight: number;
            blockTime: number;
            position: number;
            confirmations: number;
            version: number;
            locktime: number;
            size: number;
            vsize: number;
            weight: number;
            isCoinbase: boolean;
            feeSat: number | null;
            /** @description sat/vB */
            feeRate: number | null;
            inputs: {
                index: number;
                coinbaseHex: string | null;
                prevTxid: string | null;
                prevIndex: number | null;
                valueSat: number | null;
                address: string | null;
                scriptType: string | null;
                scriptSig: components["schemas"]["ScriptInput"] | null;
                witness: string[];
                sequence: number;
            }[];
            outputs: {
                index: number;
                valueSat: number;
                address: string | null;
                scriptType: string;
                script: components["schemas"]["ScriptInput"];
                spentBy: {
                    txid: string;
                    inputIndex: number;
                } | null;
            }[];
        };
        SearchResultInput: {
            /** @enum {string} */
            type: "block";
            hash: string;
            height: number;
        } | {
            /** @enum {string} */
            type: "transaction";
            txid: string;
        };
        TipInput: {
            height: number;
            hash: string;
            time: number;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
        };
        BlockSummary: {
            height: number;
            hash: string;
            time: number;
            txCount: number;
            size: number;
            weight: number;
            totalFeeSat: number;
        };
        Block: {
            height: number;
            hash: string;
            prevHash: string | null;
            nextBlockHash: string | null;
            confirmations: number;
            merkleRoot: string;
            version: number;
            bits: string;
            nonce: number;
            difficulty: number;
            time: number;
            medianTime: number;
            size: number;
            strippedSize: number;
            weight: number;
            txCount: number;
            subsidySat: number;
            totalFeeSat: number;
            rewardSat: number;
        };
        TransactionSummary: {
            txid: string;
            position: number;
            isCoinbase: boolean;
            feeSat: number | null;
            vsize: number;
            inputCount: number;
            outputCount: number;
            totalInSat: number | null;
            totalOutSat: number;
        };
        Script: {
            hex: string;
            asm: string;
        };
        Transaction: {
            txid: string;
            blockHash: string;
            blockHeight: number;
            blockTime: number;
            position: number;
            confirmations: number;
            version: number;
            locktime: number;
            size: number;
            vsize: number;
            weight: number;
            isCoinbase: boolean;
            feeSat: number | null;
            /** @description sat/vB */
            feeRate: number | null;
            inputs: {
                index: number;
                coinbaseHex: string | null;
                prevTxid: string | null;
                prevIndex: number | null;
                valueSat: number | null;
                address: string | null;
                scriptType: string | null;
                scriptSig: components["schemas"]["Script"] | null;
                witness: string[];
                sequence: number;
            }[];
            outputs: {
                index: number;
                valueSat: number;
                address: string | null;
                scriptType: string;
                script: components["schemas"]["Script"];
                spentBy: {
                    txid: string;
                    inputIndex: number;
                } | null;
            }[];
        };
        SearchResult: {
            /** @enum {string} */
            type: "block";
            hash: string;
            height: number;
        } | {
            /** @enum {string} */
            type: "transaction";
            txid: string;
        };
        Tip: {
            height: number;
            hash: string;
            time: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
